### ISSUE TITLE
exec doesn't killed linked processes properly

### ISSUE THREAD

**Issue by Gatzy118** [saleyn/erlexec#53]
When a process that has called exec:run_link dies, the exec process just exits with owner_died. I was under the assumption that this should cause exec to run the kill_cmd / kill_group or at least kill the linked OS processes.

**Comment by saleyn** [comment]
This does sound like a bug. Patches are welcome.

**Comment by Gatzy118** [comment]
Correct me if this is insane and incorrect, but I'm trying to use run_link in a supervisor child spec, e.g.

{child_id, {exec, run_link, [Cmd, [exec args...]]}, permanent, 5000, worker, [exec]}

When the supervisor is shutdown, firstly I'd expect the linked process to be killed nicely (i.e. according to kill_group, kill command etc) and then I'd want it to exit with reason shutdown. So the supervisor doesn't complain about a shutdown error. Perhaps it's worth catching the normal/shutdown case separately from the parent exiting badly?

**Comment by saleyn** [comment]
This is not going to work for several reasons, but primarily because a supervisor expects a return from the child process being `{ok, Pid}`, and exec returns `{ok, Pid, OsPid}`.  Aside from that a spawned child needs to adhere to OTP principles (e.g. processing system messages, which is handled under the hood by gen_* behaviors).
