### ISSUE TITLE
When something kills erlang process all OS processes, that have been ran from erlang process, die

### ISSUE THREAD

**Issue by Timrael** [saleyn/erlexec#55]
I faced that problem last week and I can't figure out how it happens. OS processes, that have been ran from erlang process, have parent id = 1. Maybe there are some problems with SIGHUP or SIGPIPE handling in child processes?

**Comment by Timrael** [comment]
Oh I found the line:
https://github.com/saleyn/erlexec/blob/master/c_src/exec.cpp#L982

If there is some reason why u write this?

**Comment by saleyn** [comment]
When a command gets run by `exec` with an alternative kill command: `exec:run(Cmd, [{kill, KillCmd}])`, the `KillCmd` is used to kill the spawned OS pid instead of using SIGTERM.

The transient_pids are the list of `KillCmd` processes that have been executed/forked and are still active.  At exit the line you are referring to relates to the `erlexec` port trying to kill the active "kill commands".  On that line `it->first` should not be equal to `1`, and if it is, that's a bug, so if you could troubleshoot it to find out when/why it gets assigned, that would be helpful.

**Comment by Timrael** [comment]
I directed you to the wrong line, sorry. Here is my problem:
I start new OS process in my erlang app, for example mysql. And when I send "kill -9 pid_of_erlang_app" mysql goes down. 

Another symptoms:
1. when I create OS process through erlexec it dies with erlang app
2. when I manage OS process through erlexec it does NOT die with erlang app

So I think there is problem with unlinking OS process and erlang app on creation.

**Comment by saleyn** [comment]
This is by design - the OS processes forked by erlexec are linked to it in a sense that when erlexec is signaled to be terminated (by loosing the connection to the Erlang VM that started it), it kills all forked children.

It would be possible to mark a child with "don't kill on exit" flag, and avoid killing it, though it is a new feature that would need to be implemented.  However I see very little point in this - if you don't care about the forked process to be killed on exit, then why would you want to spawn it by erlexec to begin with instead of running it externally as a service?

**Comment by Timrael** [comment]
I'm writing some kind of [Monit](https://mmonit.com/monit/) with [elixir lang](http://elixir-lang.org/) and this feature one of the main: monitoring of processes should not die with spawned processes, it should die alone and after resurrection manage spawned before processes. Your library is the only good way to execute and control OS processes from Erlang/Elixir, so if you skip this feature I will switch to another language. Please let me know about your decision.

**Comment by saleyn** [comment]
Why would you want to exit the Erlang VM?  In your design you can have an Erlang agent node running as a daemon, that would control other pids (through erlexec), just like serviced or initd do.  Your Monit interface would connect to active Erlang agent, and be able to start/control other OS pids.  If you are concerned that an Erlang node could die - in a tested system that is a highly unlikely event, and if it does then it'll restart all dependencies.

In any event, you are welcome to submit a patch to handle this.  I suppose you can pass a `'daemon'` option to `exec:run/2`, which would fork a child, and "manage" it instead of  "own" it.
