### ISSUE TITLE
Can't use non-latin characters in cmd argument

### ISSUE THREAD

**Issue by ghost** [saleyn/erlexec#91]
Any non-latin characters cause errors (sorry for example in Elixir) :

```elixir
  :exec.run_link 'тест', [:sync, :stdout]
  ** (CaseClauseError) no case clause matching: {:error, 'badarg: invalid command argument #0'}
    (erlexec) src/exec.erl:798: :exec.do_run/2

```

**Comment by saleyn** [comment]
Presently we've had no need for this feature. You are welcome to submit a PR if this is needed.

**Comment by AlexeyKuznetzov** [comment]
@saleyn Sure I'll do this, but it will be nice to get any hint or advice on implementation.

**Comment by saleyn** [comment]
First determine if the issue is on the Erlang side or on the C++ side or on both.  Try to start the exec in debug mode: `exec:start([verbose, debug])` and see what gets printed.  If the issue is with unicode support, on the C++ side it would require using std::wstring to store the command, but this needs to be ifdef'd.  A better approach would be to keep the command as a binary blob, and convert it to unicode string only when needed.

**Comment by AlexeyKuznetzov** [comment]
@saleyn Many thanks, I'll try to do this.

**Comment by saleyn** [comment]
Added support for unicode executables in the latest commit.
